In [4]:
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5])

array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("1D Array:")
print(array_1d)

print("\n2D Array (Matrix):")
print(array_2d)


1D Array:
[1 2 3 4 5]

2D Array (Matrix):
[[1 2 3]
 [4 5 6]]
